# Create a simple Pandas Series from a list: #

In [1]:
import pandas as pd
import numpy as np

In [3]:
my_list=[10,20,30,40]
my_var=pd.Series(my_list)
my_var

0    10
1    20
2    30
3    40
dtype: int64

# LABELS #

In [7]:

label=['a','b','c',6]
my_var=pd.Series(my_list,label)
my_var

a    10
b    20
c    30
6    40
dtype: int64

In [9]:
my_ser1=pd.Series([1,2,3,4],["USA","GERMANY","USSR","PAKISTAN"])
my_ser2=pd.Series([1,2,5,4],["USA","GERMANY","italy","PAKISTAN"])
my_ser1+my_ser2

GERMANY     4.0
PAKISTAN    8.0
USA         2.0
USSR        NaN
italy       NaN
dtype: float64

# DataFrames #

In [28]:
data ={
    "calories":[420,380,390],
    "duration":[50,40,45]
}
df=pd.DataFrame(data,["a","b","c"])
df

   calories  duration
a       420        50
b       380        40
c       390        45

In [29]:
df["calories"]

a    420
b    380
c    390
Name: calories, dtype: int64

In [30]:
df["new"]=[6,8,0]

In [31]:
df

   calories  duration  new
a       420        50    6
b       380        40    8
c       390        45    0

In [32]:
df.drop('new',axis=1)

   calories  duration
a       420        50
b       380        40
c       390        45

In [33]:
df

   calories  duration  new
a       420        50    6
b       380        40    8
c       390        45    0

In [34]:
df.drop('new',axis=1,inplace=True)

In [35]:
df

   calories  duration
a       420        50
b       380        40
c       390        45

In [38]:
df.loc["b"]

calories    380
duration     40
Name: b, dtype: int64

In [39]:
df.iloc[1]

calories    380
duration     40
Name: b, dtype: int64

In [40]:
df.loc["a","duration"]

np.int64(50)

In [41]:
df>0

   calories  duration
a      True      True
b      True      True
c      True      True

In [49]:
df.loc[["a","b"]]

   calories  duration
a       420        50
b       380        40

# LOADING DATA SETS #

In [51]:
df2 = pd.read_csv('data.csv')

print(df2)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [55]:
df2
# df.to_string()

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [58]:
df3=pd.read_json('airports.json')
df3

                                             airports
0   {'code': 'ATL', 'name': 'Hartsfield-Jackson At...
1   {'code': 'PEK', 'name': 'Beijing Capital Inter...
2   {'code': 'DXB', 'name': 'Dubai International',...
3   {'code': 'LAX', 'name': 'Los Angeles Internati...
4   {'code': 'HND', 'name': 'Tokyo Haneda', 'city'...
5   {'code': 'ORD', 'name': 'O'Hare International'...
6   {'code': 'LHR', 'name': 'London Heathrow', 'ci...
7   {'code': 'PVG', 'name': 'Shanghai Pudong Inter...
8   {'code': 'CDG', 'name': 'Paris Charles de Gaul...
9   {'code': 'DFW', 'name': 'Dallas/Fort Worth Int...
10  {'code': 'CAN', 'name': 'Guangzhou Baiyun Inte...
11  {'code': 'AMS', 'name': 'Amsterdam Schiphol', ...
12  {'code': 'FRA', 'name': 'Frankfurt Airport', '...
13  {'code': 'IST', 'name': 'Istanbul Airport', 'c...
14  {'code': 'SIN', 'name': 'Singapore Changi', 'c...
15  {'code': 'ICN', 'name': 'Incheon International...
16  {'code': 'DEN', 'name': 'Denver International'...
17  {'code': 'BKK', 'name': 'Suvarnabhumi Airport'...
18  {'code': 'JFK', 'name': 'John F. Kennedy Inter...
19  {'code': 'HKG', 'name': 'Hong Kong Internation...
20  {'code': 'KUL', 'name': 'Kuala Lumpur Internat...
21  {'code': 'MAD', 'name': 'Adolfo Suárez Madrid–...
22  {'code': 'SFO', 'name': 'San Francisco Interna...
23  {'code': 'MIA', 'name': 'Miami International',...
24  {'code': 'SYD', 'name': 'Sydney Kingsford Smit...
25  {'code': 'MUC', 'name': 'Munich Airport', 'cit...
26  {'code': 'BCN', 'name': 'Barcelona–El Prat', '...
27  {'code': 'YYZ', 'name': 'Toronto Pearson Inter...
28  {'code': 'MEX', 'name': 'Mexico City Internati...
29  {'code': 'NRT', 'name': 'Narita International'...

In [59]:
df3.head(10)

                                            airports
0  {'code': 'ATL', 'name': 'Hartsfield-Jackson At...
1  {'code': 'PEK', 'name': 'Beijing Capital Inter...
2  {'code': 'DXB', 'name': 'Dubai International',...
3  {'code': 'LAX', 'name': 'Los Angeles Internati...
4  {'code': 'HND', 'name': 'Tokyo Haneda', 'city'...
5  {'code': 'ORD', 'name': 'O'Hare International'...
6  {'code': 'LHR', 'name': 'London Heathrow', 'ci...
7  {'code': 'PVG', 'name': 'Shanghai Pudong Inter...
8  {'code': 'CDG', 'name': 'Paris Charles de Gaul...
9  {'code': 'DFW', 'name': 'Dallas/Fort Worth Int...

In [60]:
df2.head(5)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [61]:
df2.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [62]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [93]:
df4=pd.read_csv('student_dirty.csv')
df4

    ID       Name    Age  Gender     City  Marks Salary
0    1    Rituraj   20.0    Male  Lucknow   89.0  25000
1    2      Rahul   21.0    Male   Kanpur   75.0  30000
2    3      Priya    NaN  Female  Lucknow   91.0  28000
3    4       Aman   19.0    Male    Delhi    NaN  35000
4    5       Neha   22.0  Female      NaN   88.0  40000
5    6      Rohit   20.0    male  Lucknow   67.0    NaN
6    7     Anjali   21.0  FEMALE    Delhi   95.0  45000
7    8      Vikas    NaN    Male   Kanpur   55.0  22000
8    9      Pooja   23.0  Female  Lucknow   91.0  41000
9   10      Rahul   21.0    Male   Kanpur   75.0  30000
10  11   Rituraj    20.0    Male  Lucknow   89.0  25000
11  12      Karan  200.0    Male    Delhi   78.0  32000
12  13      Sneha   -5.0  Female     Agra   85.0  29000
13  14     Deepak   22.0    Male     Agra  999.0  34000
14  15      Kavya   21.0  Female  Lucknow   90.0    abc

# CLEANING DATA SETS #

In [96]:
new_fillna=df4.fillna(120)
new_fillna

    ID       Name    Age  Gender     City  Marks Salary
0    1    Rituraj   20.0    Male  Lucknow   89.0  25000
1    2      Rahul   21.0    Male   Kanpur   75.0  30000
2    3      Priya  120.0  Female  Lucknow   91.0  28000
3    4       Aman   19.0    Male    Delhi  120.0  35000
4    5       Neha   22.0  Female      120   88.0  40000
5    6      Rohit   20.0    male  Lucknow   67.0    120
6    7     Anjali   21.0  FEMALE    Delhi   95.0  45000
7    8      Vikas  120.0    Male   Kanpur   55.0  22000
8    9      Pooja   23.0  Female  Lucknow   91.0  41000
9   10      Rahul   21.0    Male   Kanpur   75.0  30000
10  11   Rituraj    20.0    Male  Lucknow   89.0  25000
11  12      Karan  200.0    Male    Delhi   78.0  32000
12  13      Sneha   -5.0  Female     Agra   85.0  29000
13  14     Deepak   22.0    Male     Agra  999.0  34000
14  15      Kavya   21.0  Female  Lucknow   90.0    abc

In [100]:
new_dropna=df4.dropna()
new_dropna

    ID       Name    Age  Gender     City  Marks Salary
0    1    Rituraj   20.0    Male  Lucknow   89.0  25000
1    2      Rahul   21.0    Male   Kanpur   75.0  30000
6    7     Anjali   21.0  FEMALE    Delhi   95.0  45000
8    9      Pooja   23.0  Female  Lucknow   91.0  41000
9   10      Rahul   21.0    Male   Kanpur   75.0  30000
10  11   Rituraj    20.0    Male  Lucknow   89.0  25000
11  12      Karan  200.0    Male    Delhi   78.0  32000
12  13      Sneha   -5.0  Female     Agra   85.0  29000
13  14     Deepak   22.0    Male     Agra  999.0  34000
14  15      Kavya   21.0  Female  Lucknow   90.0    abc

In [112]:
df4.isnull().sum()

ID        0
Name      0
Age       2
Gender    0
City      1
Marks     1
Salary    1
dtype: int64

In [115]:
new_fillna.isnull().sum()

ID        0
Name      0
Age       0
Gender    0
City      0
Marks     0
Salary    0
dtype: int64

In [121]:
n2=df4.fillna({"Age":15,"City":"raebareli","Marks":77,"Salary":22500})
n2

    ID       Name    Age  Gender       City  Marks Salary
0    1    Rituraj   20.0    Male    Lucknow   89.0  25000
1    2      Rahul   21.0    Male     Kanpur   75.0  30000
2    3      Priya   15.0  Female    Lucknow   91.0  28000
3    4       Aman   19.0    Male      Delhi   77.0  35000
4    5       Neha   22.0  Female  raebareli   88.0  40000
5    6      Rohit   20.0    male    Lucknow   67.0  22500
6    7     Anjali   21.0  FEMALE      Delhi   95.0  45000
7    8      Vikas   15.0    Male     Kanpur   55.0  22000
8    9      Pooja   23.0  Female    Lucknow   91.0  41000
9   10      Rahul   21.0    Male     Kanpur   75.0  30000
10  11   Rituraj    20.0    Male    Lucknow   89.0  25000
11  12      Karan  200.0    Male      Delhi   78.0  32000
12  13      Sneha   -5.0  Female       Agra   85.0  29000
13  14     Deepak   22.0    Male       Agra  999.0  34000
14  15      Kavya   21.0  Female    Lucknow   90.0    abc

In [122]:
n2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      15 non-null     int64
 1   Name    15 non-null     object
 2   Age     15 non-null     float64
 3   Gender  15 non-null     object
 4   City    15 non-null     object
 5   Marks   15 non-null     float64
 6   Salary  15 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 972.0+ bytes

In [123]:
n2.isnull().sum()

ID        0
Name      0
Age       0
Gender    0
City      0
Marks     0
Salary    0
dtype: int64

# Replace Using Mean, Median, or Mode #

In [124]:
df4

    ID       Name    Age  Gender     City  Marks Salary
0    1    Rituraj   20.0    Male  Lucknow   89.0  25000
1    2      Rahul   21.0    Male   Kanpur   75.0  30000
2    3      Priya    NaN  Female  Lucknow   91.0  28000
3    4       Aman   19.0    Male    Delhi    NaN  35000
4    5       Neha   22.0  Female      NaN   88.0  40000
5    6      Rohit   20.0    male  Lucknow   67.0    NaN
6    7     Anjali   21.0  FEMALE    Delhi   95.0  45000
7    8      Vikas    NaN    Male   Kanpur   55.0  22000
8    9      Pooja   23.0  Female  Lucknow   91.0  41000
9   10      Rahul   21.0    Male   Kanpur   75.0  30000
10  11   Rituraj    20.0    Male  Lucknow   89.0  25000
11  12      Karan  200.0    Male    Delhi   78.0  32000
12  13      Sneha   -5.0  Female     Agra   85.0  29000
13  14     Deepak   22.0    Male     Agra  999.0  34000
14  15      Kavya   21.0  Female  Lucknow   90.0    abc

In [131]:
x=df4["Age"].median()
n3=df4.fillna({"Age":x})
n3

    ID       Name    Age  Gender     City  Marks Salary
0    1    Rituraj   20.0    Male  Lucknow   89.0  25000
1    2      Rahul   21.0    Male   Kanpur   75.0  30000
2    3      Priya   21.0  Female  Lucknow   91.0  28000
3    4       Aman   19.0    Male    Delhi    NaN  35000
4    5       Neha   22.0  Female      NaN   88.0  40000
5    6      Rohit   20.0    male  Lucknow   67.0    NaN
6    7     Anjali   21.0  FEMALE    Delhi   95.0  45000
7    8      Vikas   21.0    Male   Kanpur   55.0  22000
8    9      Pooja   23.0  Female  Lucknow   91.0  41000
9   10      Rahul   21.0    Male   Kanpur   75.0  30000
10  11   Rituraj    20.0    Male  Lucknow   89.0  25000
11  12      Karan  200.0    Male    Delhi   78.0  32000
12  13      Sneha   -5.0  Female     Agra   85.0  29000
13  14     Deepak   22.0    Male     Agra  999.0  34000
14  15      Kavya   21.0  Female  Lucknow   90.0    abc

In [138]:
y=df4["Marks"].median()
n3=df4.fillna({"Marks":y})
n3

    ID       Name    Age  Gender     City  Marks Salary
0    1    Rituraj   20.0    Male  Lucknow   89.0  25000
1    2      Rahul   21.0    Male   Kanpur   75.0  30000
2    3      Priya    NaN  Female  Lucknow   91.0  28000
3    4       Aman   19.0    Male    Delhi   88.5  35000
4    5       Neha   22.0  Female      NaN   88.0  40000
5    6      Rohit   20.0    male  Lucknow   67.0    NaN
6    7     Anjali   21.0  FEMALE    Delhi   95.0  45000
7    8      Vikas    NaN    Male   Kanpur   55.0  22000
8    9      Pooja   23.0  Female  Lucknow   91.0  41000
9   10      Rahul   21.0    Male   Kanpur   75.0  30000
10  11   Rituraj    20.0    Male  Lucknow   89.0  25000
11  12      Karan  200.0    Male    Delhi   78.0  32000
12  13      Sneha   -5.0  Female     Agra   85.0  29000
13  14     Deepak   22.0    Male     Agra  999.0  34000
14  15      Kavya   21.0  Female  Lucknow   90.0    abc

In [145]:
df4["Salary"] = pd.to_numeric(df4["Salary"], errors="coerce")
df4

    ID       Name    Age  Gender     City  Marks   Salary
0    1    Rituraj   20.0    Male  Lucknow   89.0  25000.0
1    2      Rahul   21.0    Male   Kanpur   75.0  30000.0
2    3      Priya    NaN  Female  Lucknow   91.0  28000.0
3    4       Aman   19.0    Male    Delhi    NaN  35000.0
4    5       Neha   22.0  Female      NaN   88.0  40000.0
5    6      Rohit   20.0    male  Lucknow   67.0      NaN
6    7     Anjali   21.0  FEMALE    Delhi   95.0  45000.0
7    8      Vikas    NaN    Male   Kanpur   55.0  22000.0
8    9      Pooja   23.0  Female  Lucknow   91.0  41000.0
9   10      Rahul   21.0    Male   Kanpur   75.0  30000.0
10  11   Rituraj    20.0    Male  Lucknow   89.0  25000.0
11  12      Karan  200.0    Male    Delhi   78.0  32000.0
12  13      Sneha   -5.0  Female     Agra   85.0  29000.0
13  14     Deepak   22.0    Male     Agra  999.0  34000.0
14  15      Kavya   21.0  Female  Lucknow   90.0      NaN

In [143]:
z=df4["Salary"].median()
n3=df4.fillna({"Salary":z})
n3

    ID       Name    Age  Gender     City  Marks   Salary
0    1    Rituraj   20.0    Male  Lucknow   89.0  25000.0
1    2      Rahul   21.0    Male   Kanpur   75.0  30000.0
2    3      Priya    NaN  Female  Lucknow   91.0  28000.0
3    4       Aman   19.0    Male    Delhi    NaN  35000.0
4    5       Neha   22.0  Female      NaN   88.0  40000.0
5    6      Rohit   20.0    male  Lucknow   67.0  30000.0
6    7     Anjali   21.0  FEMALE    Delhi   95.0  45000.0
7    8      Vikas    NaN    Male   Kanpur   55.0  22000.0
8    9      Pooja   23.0  Female  Lucknow   91.0  41000.0
9   10      Rahul   21.0    Male   Kanpur   75.0  30000.0
10  11   Rituraj    20.0    Male  Lucknow   89.0  25000.0
11  12      Karan  200.0    Male    Delhi   78.0  32000.0
12  13      Sneha   -5.0  Female     Agra   85.0  29000.0
13  14     Deepak   22.0    Male     Agra  999.0  34000.0
14  15      Kavya   21.0  Female  Lucknow   90.0  30000.0